GamaPedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("GamePediaApp.urls")),
]

GamePediaApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout_view, name='logout'),
    path('newgame', views.new_game, name='new_game'),
    path('getgames/<int:page_number>', views.getgames, name='getgames'),
    path('quicksearch/<str:input>', views.quicksearch, name='quicksearch'),
    path('game/<int:game_id>', views.game, name="game"),
    path('postrating', views.postrating, name='postrating'),
    path('genres', views.grnres, name='genres'),
    path('genres/<str:genre>', views.genregames),
    path('getgenregames/<str:genre>/<int:page_number>', views.getgenregames),
    path('quicksearchdev/<str:input>', views.devsearch),
    path('quicksearchpub/<str:input>', views.pubsearch),
    path('dev/<int:dev_id>', views.developer),
    path('getdevgames/<int:genre_id>/<int:page_num>', views.getdevgames),
    path('addtopl', views.addtoplaylist),
    path('playlist', views.playlist),
    path('getplaylist/<int:page_number>', views.getplaylist),
    path('unverifiedgames', views.unverifiedgames),
    path('getunverifeiedgame/<int:page_number>', views.getunverifeiedgames),
    path('unverifiedgame/<int:game_id>', views.unverfiedgame),
    path('verifyordelete', views.verifyordelete),
]

GamePediaApp/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

# Create your models here.

genres = ['Action', 'Adventure', 'Battle Royale', "Beat 'em up", 'Board game', 'Co-Op', 'Competitive', 'Educational', 'Esports', 'FPS', 'Fighting', 'Horror', 'Interactive movie', 'MMO', 'Metroidvania', 'Multiplayer', 'Party', 'Platform', 'Puzzles', 'RPG', 'Racing', 'Rhythm', 'Roguelikes', 'Sandbox', 'Shooter', 'Simulation', 'Sports', 'Stealth', 'Strategy', 'Survival', 'Tactical', 'Text Based', 'Third Person Shooting', 'Tower defense', 'Turn-based', 'Visual novel', 'open world', 'Zombie', 'Other']

def avg(lst):
    if len(lst) == 0:
        return '--'
    return float(sum(lst) / len (lst))

class User(AbstractUser):
    playlist = models.ManyToManyField('Game' ,blank=True, related_name='playlist')


class Game(models.Model):
    title = models.CharField(blank=False, max_length=256)
    poster = models.CharField(blank=False, max_length=1000)
    description = models.CharField(blank=False, max_length=4096)
    relasedate = models.DateField(auto_created=False)
    genres = models.ManyToManyField('Genre', blank=False, related_name='genres')
    ratings = models.ManyToManyField('Rating', blank=True, related_name='ratings')
    developer = models.ForeignKey('Developer', on_delete=models.CASCADE, related_name='games')
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE, related_name='games')
    verified = models.BooleanField(default=False, blank=False)

    def serialize(self):
        return {
            'id': self.id,
            'title': self.title,
            'poster': self.poster,
            'description': self.description,
            'relasedate': self.relasedate.strftime("%b %d %Y, %I:%M %p"),
            'genres': [genre.genre for genre in self.genres.all()],
            'ratings': [{'reviewer': rating.reviewer.id, 'rating': rating.rating, 'review': rating.review} for rating in self.ratings.all()],
            'avg_rating' : self.avg_rating(),
            'developer': self.developer.developer,
            'dev_id': self.developer.id,
            'publisher': self.publisher.publisher,
            'pub_id': self.publisher.id
        }
    
    def avg_rating(self):
            rating = avg([float(rating.rating) for rating in self.ratings.all()])
            if rating == '--':
                return -1
            else:
                return round(rating, 1)
    
    def __str__(self) -> str:
        return self.title



class Genre(models.Model):
    genre = models.CharField(blank=False, choices=[(genres.index(genre) + 1, genre) for genre in genres], max_length=256, default='Other')
    def __str__(self) -> str:
        return str(self.genre)


class Developer(models.Model):
    developer = models.CharField(blank=False, unique=True, max_length=512)
    verified = models.BooleanField(default=False, blank=False)


class Publisher(models.Model):
    publisher = models.CharField(blank=False, unique=True, max_length=512)
    verified = models.BooleanField(default=False, blank=False)


class Rating(models.Model):
    reviewer = models.ForeignKey('User', on_delete=models.CASCADE, related_name='reviews')
    rating = models.FloatField(blank=False ,validators=[MinValueValidator(0.0), MaxValueValidator(10.0)])
    review = models.CharField(blank=True, max_length=2064)

GamePediaApp/forms.py
from django import forms
from .models import genres

pubs =['CDProjectRed', 'Ubisoft', 'konami', 'Activision', 'Square Enix', 'Electronic Arts ', 'Epic Games']
devs = ['CDProjectRed', 'Ubisoft', 'konami', 'Activision', 'Square Enix', 'Electronic Arts ', 'Epic Games']

class New_Game_Form(forms.Form):
    title = forms.CharField(max_length=128, required=True, widget=forms.TextInput(attrs={'class': 'mysuperform', 'autocomplete': 'off'}))
    image = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'mysuperform', 'autocomplete': 'off'}))
    description = forms.CharField(required=True, max_length=4096, widget=forms.Textarea(attrs={'class': 'mysuperform', 'autocomplete': 'off'}))
    release_date = forms.DateField(required=True, widget=forms.TextInput(attrs={'class': 'mysuperform', 'type': 'date',  'autocomplete': 'off'}))
    genres =forms.CharField(required=True ,widget=forms.Select(choices=[(genres.index(genre)+1, genre) for genre in genres], attrs={'multiple': True, 'class': 'mysuperformselect', 'required': True}), label='Genres (Hold CTRL to select multiple):')
    dev = forms.CharField(required=True,widget=forms.TextInput(attrs={ 'class': 'mysuperform', 'type': 'text', 'autocomplete': 'off'}), label='Developer:')
    pub = forms.CharField(required=True,widget=forms.TextInput(attrs={ 'class': 'mysuperform', 'type': 'text', 'autocomplete': 'off'}), label='Publisher:')


class Review_Form(forms.Form):
    rating = forms.FloatField(max_value=10, min_value=0, required=True, widget=forms.NumberInput(attrs={'class': 'rating_input'}))
    review = forms.CharField(max_length=4096, required=False, widget=forms.Textarea(attrs={'class': 'rating_review'}))

GamePediaApp/views.py
import json
from math import ceil
from django.shortcuts import render
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .models import User, Game, Genre, Developer, Publisher, Rating,genres
from .forms import New_Game_Form, Review_Form
from django.db.models import Q
from django.contrib.admin.views.decorators import staff_member_required

# Create your views here.

def index(request):
    lenght = ceil((Game.objects.filter(verified=True).count())/28)
    return render(request, 'gamepedia/index.html',{
        'max_page' : lenght
    })


@csrf_exempt
def login(request):
    if request.method == 'GET':
        return render(request, 'gamepedia/login.html')
    elif request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["Password"]
        user = authenticate(username=username, password=password)

        # Check if authentication successful
        if user is not None:
            auth_login(request, user)
            return HttpResponseRedirect(reverse("home"))
        else:
            return render(request, "gamepedia/login.html", {
                "message_login": "Invalid username and/or password."
            })


@csrf_exempt
def register(request):
    if request.method == "POST":
        username = request.POST["createusername"]

        # Ensure password matches confirmation
        password = request.POST["createpassword"]
        confirmation = request.POST["passwordconfirm"]
        if password != confirmation:
            return render(request, "gamepedia/login.html", {
                "message_register": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, password)
            user.set_password(password)
            user.save()
        except IntegrityError:
            return render(request, "gamepedia/login.html", {
                "message_register": "Username already taken."
            })
        auth_login(request, user)
        return HttpResponseRedirect(reverse("home"))
    else:
        return render(request, "gamepedia/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("home"))


@login_required
@csrf_exempt
def new_game(request):
    if request.method == 'GET':
        return render(request, 'gamepedia/new_game.html', {
            'new_game_form': New_Game_Form,
            'devs' : ['CDProjectRed', 'Ubisoft', 'konami', 'Activision', 'Square Enix', 'Electronic Arts ', 'Epic Games'],
            'pubs' : ['CDProjectRed', 'Ubisoft', 'konami', 'Activision', 'Square Enix', 'Electronic Arts ', 'Epic Games'],
        })
    elif request.method == 'POST':
        data = New_Game_Form(request.POST) 
        if data.is_valid():
            if Developer.objects.filter(developer=data.cleaned_data['dev']).exists():
                dev = Developer.objects.get(developer=data.cleaned_data['dev'])
            else:
                dev = Developer(developer=data.cleaned_data['dev'])
                dev.save()

            if Publisher.objects.filter(publisher=data.cleaned_data['pub']).exists():
                pub = Publisher.objects.get(publisher=data.cleaned_data['pub'])
            else:
                pub = Publisher(publisher=data.cleaned_data['pub'])
                pub.save()


            game_genres = request.POST.getlist('genres')
            game = Game(title=data.cleaned_data['title'], poster=data.cleaned_data['image'], description=data.cleaned_data['description'], relasedate=data.cleaned_data['release_date'], developer=dev, publisher=pub)
            game.save()
            for genre in game_genres:
                game.genres.add(Genre.objects.get(id=genre))
            game.save()
            return(HttpResponseRedirect(reverse('home')))


def getgames(request, page_number):
    games = Game.objects.filter(verified=True)
    games = sorted(games, key=lambda x: x.avg_rating(), reverse=True)
    result = [game.serialize() for game in games]
    result = Paginator(result, 28)
    return JsonResponse(result.page(page_number).object_list, safe=False)


def quicksearch(request, input):
    games = Game.objects.filter(title__contains=input, verified=True)[:5]
    result = [game.serialize() for game in games]
    return JsonResponse(result, safe=False)


def game(request, game_id):
    userreview = None
    reviewd = False
    reviews = None
    game = Game.objects.get(id=game_id)
    if request.user.is_authenticated:
        reviewd = game.ratings.filter(reviewer=request.user).exists()
        user = User.objects.get(id=request.user.id)
        reviews = game.ratings.filter(~Q(reviewer=request.user))
        is_paylist = game in user.playlist.all()
        if game.ratings.filter(reviewer=request.user).exists():
            userreview = game.ratings.get(reviewer=request.user)
    else:
        user = None
        is_paylist = None
    return render(request, 'gamepedia/game.html', {
        'game': game,
        'genres' : [genre.genre for genre in game.genres.all()],
        'review_form': Review_Form,
        'reviewd': reviewd,
        'userreview': userreview,
        'reviews': reviews,
        'avg_rating': game.serialize()['avg_rating'],
        'is_paylist': is_paylist,
    })

@csrf_exempt
@login_required
def postrating(request):
    data = json.loads(request.body)
    task = data.get('task')
    if task == 'post':
        rating_value = data.get('rating')
        review = data.get('review')
        game = Game.objects.get(id=data.get('game_id'))
        rating = Rating(reviewer=request.user, rating=float(rating_value), review=review)
        rating.save()
        game.ratings.add(rating)
        game.save()
        return JsonResponse({'message': 'rated succefully'})
    elif task == 'change':
        game = Game.objects.get(id=data.get('game_id'))
        rating = game.ratings.get(reviewer=request.user)
        rating_value = data.get('rating')
        review = data.get('review')
        rating.rating = rating_value
        rating.review = review
        rating.save()
        game.save()
        return JsonResponse({'message': 'rating changed succefully'})


def grnres(request):
    return render(request, 'gamepedia/genres.html',{
        'genres': [genre.genre for genre in Genre.objects.all()]
    })

def genregames(request, genre):
        genreo = Genre.objects.get(genre=genre)
        lenght = ceil((Game.objects.filter(genres=genreo ,verified=True).count())/28)
        return render(request, 'gamepedia/genre.html', {
            'genre': genre,
            'max_page' : lenght
        })


def getgenregames(request, genre, page_number):
    genre_object = Genre.objects.get(genre=genre)
    games = Game.objects.filter(genres=genre_object, verified=True)
    games = sorted(games, key=lambda x: x.avg_rating(), reverse=True)
    result = [game.serialize() for game in games]
    result = Paginator(result, 28)
    return JsonResponse(result.page(page_number).object_list, safe=False)


def devsearch(request, input):
    devs = Developer.objects.filter(developer__contains=input, verified=True)[:5].all()
    result = [{'dev': dev.developer} for dev in devs]
    return JsonResponse(result, safe=False)

def pubsearch(request, input):
    devs = Publisher.objects.filter(publisher__contains=input, verified=True)[:5].all()
    result = [{'pub': dev.publisher} for dev in devs]
    return JsonResponse(result, safe=False)


def getdevgames(request, genre_id, page_num):
    dev_object = Developer.objects.get(id=genre_id)
    games = Game.objects.filter(developer=dev_object, verified=True)
    games = sorted(games, key=lambda x: x.avg_rating(), reverse=True)
    result = [game.serialize() for game in games]
    result = Paginator(result, 28)
    return JsonResponse(result.page(page_num).object_list, safe=False)


def developer(request, dev_id):
    dev = Developer.objects.get(id=dev_id)
    lenght = ceil((Game.objects.filter(developer=dev ,verified=True).count())/28)
    return render(request, 'gamepedia/dev.html', {
        'dev': dev,
        'max_page' : lenght,
    })

@csrf_exempt
def addtoplaylist(request):
    data = json.loads(request.body)
    game = Game.objects.get(id=data.get('game_id'))
    user = User.objects.get(id=request.user.id)
    task = data.get('task')
    if task == 'add':
        user.playlist.add(game)
        user.save()
        return JsonResponse({'message': 'Added to playlit succefully'})
    else:
        user.playlist.remove(game)
        user.save()
        return JsonResponse({'message': 'remove from playlit succefully'})

@login_required
def playlist(request):
    user = User.objects.get(id=request.user.id)
    lenght = ceil((user.playlist.all().count()) / 28)
    return render(request, 'gamepedia/palylist.html', {
        'max_page' : lenght
    })

@login_required
def getplaylist(request, page_number):
    user = User.objects.get(id=request.user.id)
    games = user.playlist.all()
    games = sorted(games, key=lambda x: x.avg_rating(), reverse=True)
    result = [game.serialize() for game in games]
    result = Paginator(result, 10)
    return JsonResponse(result.page(page_number).object_list, safe=False)

@staff_member_required
def unverifiedgames(request):
    lenght = ceil((Game.objects.filter(verified=False).count())/28)
    return render(request, 'gamepedia/unverifiedgames.html',{
        'max_page' : lenght
    })


@staff_member_required
def getunverifeiedgames(request, page_number):
    games = Game.objects.filter(verified=False)

GamePediaApp/templates/gamepedia/dev.html
{% extends 'gamepedia/layout.html' %}
{% load static %}
{% block title %}GamePedia{% endblock %}
{% block body %}
<link rel="stylesheet" href="{% static 'gamepedia/index.css' %}">
<script src="{% static 'gamepedia/dev.js' %}"></script>
<input type="hidden" id="max_page" value="{{ max_page }}">
<hr>
<input type="hidden" value="{{ dev.id }}" id="developer_id">
<h2 style="color: #e5e4e2; padding-left: 20px;">{{ dev.developer }}:</h2>
<div class="games">

</div>
{% endblock %}

GamePediaApp/templates/gamepedia/game.html
{% extends 'gamepedia/layout.html' %}
{% load static %}
{% block title %}{{ game.title }}{% endblock %}
{% block body %}
<link rel="stylesheet" href="{% static 'gamepedia/game.css' %}">
<script src="{% static 'gamepedia/game.js' %}"></script>
<input type="hidden" value="{{ game.id }}" id="game_id">
<div class="content">
    <div class="infocontainer">
        <div class="gametitle">{{ game.title }}:</div>
        <div class="imgcontainer"><img src="{{ game.poster}}" alt="{{ game.title }} cover"></div>
        <div class="gamedescription">{{ game.description }}</div>
        <div class="gamegenres"><strong>Genres:</strong> {% for genre in genres %} <span><a href="/genres/{{ genre }}">{{ genre }},&nbsp</a></span>{% endfor %}</div>
        <div class="gamedev"><strong>Developer:</strong> <a href="/dev/{{game.developer.id}}">{{ game.developer.developer }}</a></div>
        <div class="gamepub"><strong>Publisher:</strong> {{ game.publisher.publisher }}</div>
        <div class="ratingandwl">{% if user.is_authenticated %}<div class="wl" data-add="{{ is_paylist }}" onclick="playlistchange()">+</div>{% endif %}<div class="rating">{%if avg_rating|floatformat:1 != "-1.0" %}{{ avg_rating|floatformat:1 }} {% else %} NA{% endif %}</div></div>
    </div>
    {% if user.is_authenticated %}
        {% if reviewd %}
            <div class="user_review">
                <h3>Your review:</h3>
                <div class="userreviewtext">{{ userreview.review }}</div>
                {% if userreview.rating == 10 %}
                <div class="userreviewrating">10</div>
                {% else %}
                <div class="userreviewrating">{{ userreview.rating|floatformat:1}}</div>
                {% endif %}
                <button class="changereview" onclick="changereviewview()">Change your Review</button>
            </div>
            <div class="review_form" style="display: none;">
                <h3>Leave a Review:</h3>
                <tr>
            <th><label for="id_rating">Rating:</label></th><td>
            <input type="number" name="rating" class="rating_input" min="0" max="10" required id="id_rating"></td>
            </tr>
            <tr>
            <th><label for="id_review">Review:</label></th><td>
            <textarea name="review" cols="40" rows="10" class="rating_review" maxlength="4096" id="id_review"></textarea>
            </td>
            </tr>
            <button class="submitbauuton" onclick="changereview()" style="width: 200px;">change review</button>
            </div>
        {% else %}
        <div class="review_form">
            <h3>Leave a Review:</h3>
            <tr>
            <th><label for="id_rating">Rating:</label></th><td>
            <input type="number" name="rating" class="rating_input" min="0" max="10" required id="id_rating"></td>
            </tr>
            <tr>
            <th><label for="id_review">Review:</label></th><td>
            <textarea name="review" cols="40" rows="10" class="rating_review" maxlength="4096" id="id_review"></textarea>
            </td>
            </tr>
            <form action=""><button class="submitbauuton" onclick="postreview()">Submit</button></form>
            </div>
        {% endif %}
    {% endif %}
    <div class="allreviews" style="height: 100px;">
        <hr style="background-color: white;">
        <h2>Users Reviews:</h2>
        {% for review in reviews %}
            <div class="user_review" style="min-height: 100px;">
                <h3>{{ review.reviewer.username }}</h3>
                <div class="userreviewtext">{{ review.review }}</div>
                {% if review.rating == 10 %}
                <div class="userreviewrating">10</div>
                {% else %}
                <div class="userreviewrating">{{ review.rating|floatformat:1}}</div>
                {% endif %}
            </div>
        {% empty %}
        <h4>No Reviews yet</h4>
        {% endfor %}
    </div>
</div>
{% endblock %}

GamePediaApp/templates/gamepedia/genre.html
{% extends 'gamepedia/layout.html' %}
{% load static %}
{% block title %}GamePedia{% endblock %}
{% block body %}
<link rel="stylesheet" href="{% static 'gamepedia/index.css' %}">
<script src="{% static 'gamepedia/genre.js' %}"></script>
<input type="hidden" id="max_page" value="{{ max_page }}">
<hr>
<input type="hidden" value="{{ genre }}" id="genre">
<h2 style="color: #e5e4e2; padding-left: 20px;">{{ genre }}:</h2>
<div class="games">

</div>
{% endblock %}

GamePediaApp/templates/gamepedia/genres.html
{% extends 'gamepedia/layout.html' %}
{% load static %}
{% block title %}Genres{% endblock %}
{% block body %}
<link rel="stylesheet" href="{% static 'gamepedia/genres.css' %}">
<hr>
<div class="genres">
    {% for genre in genres %}
    <a href="genres/{{ genre }}"><div class="genre">{{ genre }}</div></a>
    {% endfor %}
</div>
{% endblock %}

GamePediaApp/templates/gamepedia/index.html
{% extends 'gamepedia/layout.html' %}
{% load static %}
{% block title %}GamePedia{% endblock %}
{% block body %}
<link rel="stylesheet" href="{% static 'gamepedia/index.css' %}">
<input type="hidden" id="max_page" value="{{ max_page }}">
<script src="{% static 'gamepedia/index.js' %}"></script>
<div class="mysearch">
  <div class="input-and-result">
    <form action="#">
      <input type="search" class="search-bar" placeholder="Search" autocomplete="off">
      <button type="submit" class="mysearch_button">&#x1F50E</button>
    </form>
    <div>
      <ul class="qiucksearch_results" style="display: none;"></ul>
    </div>
  </div>
</div>
<hr>
<div class="games">
</div>
{% endblock %}

GamePediaApp/templates/gamepedia/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'gamepedia/layout.js' %}"></script> 
    <link rel="stylesheet" href="{% static 'gamepedia/layout.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color: #2c3a5c;">
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark" style="z-index: 3000;">
        <a class="navbar-brand" href="/">GamePedia</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#" id="logout">{{ request.user.username }}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/newgame">Add a game</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/playlist">Playlist</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="/login">Login</a>
                </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="/genres">Genres</a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="/unverifiedgames">Unvirefied Games</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
<div class="body">
  {% block body %}
  {% endblock %}
</div>
<dialog data-modal style="display: none;">
  <div>Are you sure you want to log-out?</div>
  <button class="btn btn-outline-success" data-close-modal>No</button>
  <a href="/logout"><button class="btn btn-danger" data-logout>Yes</button></a>
</dialog>
</body>
</html>

GamePediaApp/templates/gamepedia/login.html
{% extends 'gamepedia/layout.html' %}
{% load static %}
{% block title %}Login{% endblock %}

{% block body %}
    <link href="{% static 'gamepedia/login.css' %}" rel="stylesheet">
    <script src="{% static 'gamepedia/login.js' %}"></script>

    <div class="bodycontainer"> 
        <div class="mycontainer" id="login">
            <h3>Login</h3>
            <form action="/login" method="post">
                <input id="username" placeholder="username" name="username" autocomplete="off" autofocus class="username" required>
                <input type="password" id="password" name="Password" placeholder="Password" class="password" required>
                <h5>{{ message_login }}</h5>
                <div class="alternavie">Don't an Account? <span onclick="showcreate()">Create One</span></div>
                <input type="submit" class="login-button" value="Login">
            </form>
        </div>
        <div class="mycontainer" id="create">
            <h3>Create Account</h3>
            <form action="/register" method="post">
                <input id="createusername" placeholder="username" name="createusername" autocomplete="off" class="username" required>
                <input type="password" placeholder="Password" name="createpassword" id="createpassword" class="password" required>
                <input type="password" placeholder="confirm Password" name="passwordconfirm" id="passwordconfirm" class="passwordconfirm" required>
                <h5>{{ message_register }}</h5>
                <div class="alternavie">You have an Account? <span onclick="showlogin()">login</span></div>
                <input type="submit" class="login-button" value="Create Account">
            </form>
        </div>
    </div>
{% endblock %}

GamePediaApp/templates/gamepedia/new_game.html
{% extends 'gamepedia/layout.html' %}
{% load static %}
{% block title %}New Game{% endblock %}
{% block body %}
<link href="{% static 'gamepedia/newgame.css' %}" rel="stylesheet">
<script src="{% static 'gamepedia/newgame.js' %}"></script>

<div class="form_container">
    <form action="/newgame" method="POST">
        <div class="form-group">
        {{ new_game_form }}
        </div>
        <button type="submit" class="btn btn-primary" id="submit">Submit</button>
</form>
</div>

{% endblock %}